---
title: "Homework 3"
author: "Raul Torres Aragon"
date: "9/26/2023"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
#load("hw3_en.Rdata")
```


# Q1
Apply Newton's method with the initial guess $x_{(0)} = 1$.  

Recall  $f(x) \approx f(x_0) + (x-x_0)f'(x_0)$.  
For $f(x)=0$, we have $0=f(x)\approx f(x_0) + (x-x_0)f'(x_0)$.  
Hence $x \approx x_0 - \frac{f(x_0)}{f'(x_0)}$.  

## (a)
$f(x) = x^3 + x^2 -1 = 0$  
$f'(x) = 3x^2 + 2x$

Step 1:  
For initial point $x_{(0)} = 1$, we obtain $x \approx 1 - \frac{(1)^3+(1)^3-1}{3(1)^2+2(1)} = \frac{4}{5}$  

Step 2:  
For $x_{(1)} := \frac{4}{5}$, we obtain $x \approx \frac{4}{5} - \frac{(4/5)^3+(4/5)^3-1}{3(4/5)^2+2(4/5)} \approx 0.7568$



## (b)  
$f(x) = x^2 + \frac{1}{x+1}-3x = 0$  
$f'(x) = 2x - (x+1)^{-2}-3$

Step 1:  
For initial point $x_{(0)} = 1$, we obtain $x \approx 1 - \frac{(1)^2+(1+1)^{-1}-3(1)}{2(1)-(1+1)^{-2}-3} = -\frac{1}{5}$  

Step 2:  
For $x_{(1)} := -\frac{1}{5}$, we obtain $x \approx -\frac{1}{5} - \frac{(-\frac{1}{5})^2+(-\frac{1}{5}+1)^{-1}-3(-\frac{1}{5})}{2(-\frac{1}{5})-(+1)^{-2}-3} \approx .1809$



## (c)  
$f(x) = 5x-10=0$  
$f'(x) = 5$  

Step 1:  
For initial point $x_{(0)} = 1$, we obtain $x \approx 1 - \frac{5(1)-10}{5} = 2$  

Step 2:  
For $x_{(1)} := 2$, we obtain $x \approx 2 - - \frac{5(2)-10}{5} = 2$  



# Q2  
Use Newton's method to minimize the function (known as Powell function):  

$$
f(x_1,x_2,x_3,x_4) = (x_1+10x_2)^2 + 5(x_3-x_4)^2+(x_2-2x_3)^4+10(x_1-2x_4)^4
$$  
Use as the starting point $\boldsymbol{x}_{(0)} = (3,-1,0,1)^T$. Perform three iterations. (Do not program or use any computer package!)  

Recall the multivariable Newton-Raphson method is:  
$\boldsymbol{x} \approx \boldsymbol{x}_0 - \nabla^2f(\boldsymbol{x}_0)^{-1}\nabla f(\boldsymbol{x}_0)$.  

Thus, 
$$
\nabla f(\boldsymbol{x}) =  
\begin{bmatrix}
2(x_1+10x_2) + 0 + 0 + 40(x_1-2x_4)^3 \\
20(x_1 + 10x_2) + 0 + 4(x_2-2x_3)^3 + 0 \\
0 + 10(x_3-x_4) -8(x_2-2x_3)^3 + 0 \\
0 + -10(x_3-x_4) + 0 -80(x_1-2x_4)^3
\end{bmatrix}
$$  
and,  
$$
\nabla^2 f(\boldsymbol{x}) =  
\begin{bmatrix}
2+120(x_1-2x_4)^2 & 20 & 0 & -240(x_1-2x_4) \\
20 & 12(x_2-2x_3)^2+200 & -24(x_2-2x_3)^2 & 0 \\
0 & -24(x_2-2x_3)^2 & -48(x_2-2x_3)^2+10 & -10 \\
-240(x_1-2x_4) & 0 & -10 & 480(x_1-2x_4)^2+10
\end{bmatrix}
$$  
Step 1:  
$\boldsymbol{x}_0 = \begin{bmatrix} 3 & -1 & 0 & 1 \end{bmatrix}^T$  

$f(\boldsymbol{x}_{(0)}) = (3 + 10(-1))^2 + 5(0-1)^2+(-1-2(0))^4+10(3-2(1))^4 = 65$

$$
\nabla f(\boldsymbol{x}_{(0)}) =  
\begin{bmatrix}
26 \\
-144 \\
-2 \\
-60
\end{bmatrix}
$$  

and,  
$$
\begin{aligned}
\nabla^2 f(\boldsymbol{x}_{(0)})^{-1} &=  
\begin{bmatrix}
122 & 20 & 0 & -240 \\
20 & 212 & -24 & 0 \\
0 & -24 & -38 & -10 \\
-240 & 0 & -10 & 490
\end{bmatrix}^{-1} \\
&= 
\begin{bmatrix}
0.3660 & -0.0372 & -0.0236 & 0.1788 \\
-0.0372 &  0.00818 & -0.00037 & -0.0182 \\
-0.0236 & -0.00037 & -0.02292 & -0.0120 \\
0.1788 & -0.0182 & -0.01200 &  0.08938
\end{bmatrix}
\end{aligned}
$$  
So, $\boldsymbol{x}_{(1)} = (-1.19, 0.05, -0.207, -0.935)^T$  

Step 2  

$\boldsymbol{x}_{(1)} = \begin{bmatrix} -1.19 & 0.05 & -0.207 & -0.935 \end{bmatrix}^T$  


$f(\boldsymbol{x}_{(1)}) = (-1.19 + 10(0.05))^2 + 5(-.207+0.935)^2+(-1-2(-0.207))^4+10(-1.19-2(-0.935))^4 \approx 5.273$

$$
\nabla f(\boldsymbol{x}_{(1)}) =  
\begin{bmatrix}
11.10 \\
-13.18 \\
6.47 \\
-34.8
\end{bmatrix}
$$  

and,  
$$
\begin{aligned}
\nabla^2 f(\boldsymbol{x}_{(0)})^{-1} &=  
\begin{bmatrix}
57.16 & 20 & 0 & -110.32 \\
20 & 202.60 & -5.21 & 0 \\
0 & -5.21 & -0.42 & -10 \\
-110.32 & 0 & -10 & 230.64
\end{bmatrix}^{-1} \\
&= 
\begin{bmatrix}
0.04 & -0.01 & -0.207 & 0.014 \\
-0.010 &  0.006 & 0.017 & -0.004 \\
-0.207 & 0.017 & -0.117 & -0.104 \\
0.014 & -0.04 & -0.104 &  0.006
\end{bmatrix}
\end{aligned}
$$  
and thus $\boldsymbol{x}_{(2)} = (-0.03, -0.06, -0.54, -0.24)^T$  

Step 3  

$f(\boldsymbol{x}_{(2)}) = (-0.03 + 10(-0.06))^2 + 5(-0.54+0.24)^2+(-0.06-2(-0.54))^4+10(-0.03-2(-0.24))^4 \approx 2.237$  

$$
\nabla f(\boldsymbol{x}_{(2)}) =  
\begin{bmatrix}
3.58 \\
3.01 \\
-13.01 \\
-9.93
\end{bmatrix}
$$  
$$
\begin{aligned}
\nabla^2 f(\boldsymbol{x}_{(0)})^{-1} &=  
\begin{bmatrix}
26.91 & 20 & 0 & -49.82 \\
20 & 213.94 & -27.89 & 0 \\
0 & -27.89 & -45.79 & -10 \\
-49.82 & 0 & -10 & 109.64
\end{bmatrix}^{-1} \\
&= 
\begin{bmatrix}
 0.403 & -0.039 & -0.015 &  0.182 \\
-0.039 &  0.008 & -0.001 & -0.018 \\
-0.015 & -0.001 & -0.019 & -0.008 \\
 0.182 & -0.018 & -0.008 &  0.091
\end{bmatrix}
\end{aligned}
$$  
and thus $\boldsymbol{x}_{(3)} = (0.24, -0.08, -0.82, -0.05)^T$  


# Q3  

Consider the problem of estimating gene frequencies of blood antigens A and B by observing the four blood groups: AB, A, B, and O. Denote the gene frequencies of A and B by $\theta_1$ and $\theta_2$. respectively, and also the probabilities of the four blood groups by $\pi_1$, $\pi_2$, $\pi_3$, $\pi_4$. These probabilities are functions of $\theta_1$ and $\theta_2$:  

$$
\begin{aligned}
\pi_1(\theta_1, \theta_2) &= 2\theta_1 \theta_2, \\
\pi_2(\theta_1, \theta_2) &= \theta_1(2-\theta_1-2\theta_2), \\
\pi_3(\theta_1, \theta_2) &= \theta_2(2-\theta_2-2\theta_1), \\
\pi_4(\theta_1, \theta_2) &= (1-\theta_1-\theta_2)^2
\end{aligned}
$$  
Assume that the likelihood can be treated as a multinomial with observed frequencies $y_1$, $y_2$, $y_3$, and $y_4$ with $\sum_{i=1}^4y_i=n$.  

## (a)  
Identify the likelihood function $L(\boldsymbol{\theta})$, the log likelihood $l(\boldsymbol{\theta})$.  

The pdf of a multinomial random variable is:  
$$
\begin{aligned}
{n! \choose y_1!\dots y_2!} \prod_{i=1}^4 \pi_i^{y_i} &= n!\prod_{i=1}^4 \frac{\pi_i^{y_i}}{y_i!}
\end{aligned}
$$  
Substituting $\pi_i$ with the expression as functions of $\theta_1$ and $\theta_2$, we get:  

$$
\begin{aligned}
L(\theta_1, \theta_2) &= n!\frac{2\theta_1\theta2}{y_1!} 
\frac{\theta_1(2-\theta_1-2\theta_2)}{y_2!} 
\frac{\theta_2(2-\theta_2-2\theta_1)}{y_3!}
\frac{(1-\theta_1-\theta_2)^2}{y_4!}
\end{aligned}
$$  
Taking $log[L(\theta_1,\theta_2)]$ we obtain the log-likelihood function:  
$$
\begin{aligned}
l(\theta_1, \theta_2) &= log\bigg\{n!\frac{2\theta_1\theta2}{y_1!} 
\frac{\theta_1(2-\theta_1-2\theta_2)}{y_2!} 
\frac{\theta_2(2-\theta_2-2\theta_1)}{y_3!}
\frac{(1-\theta_1-\theta_2)^2}{y_4!}\bigg\} \\
&= log(n!) + log(2\theta_1\theta_2 \theta_1(2-\theta_1-2\theta_2)\theta_2(2-\theta_2-2\theta_1)(1-\theta_1)(1-\theta_1-\theta_2)^2) - \sum_{i=1}^4log(y_i!)
\end{aligned}
$$  


## (b)  
Derive the score function $\nabla l(\boldsymbol{\theta})=l'(\boldsymbol{\theta})$ and the Hessian of the likelihood $\boldsymbol{H}(\boldsymbol{\theta})=\nabla^2l(\boldsymbol{\theta})$.  

The score function is the gradient vector of $l(\theta_1, \theta_2) = \boldsymbol{0}$. So,  
$$
\begin{aligned}
\nabla l(\theta_1,\theta_2) &= 
\begin{bmatrix}
\frac{\partial l}{\partial \theta_1} && \frac{\partial l}{\partial \theta_2}
\end{bmatrix} \\ 
&= \begin{bmatrix}
\frac{1}{\theta_1}+\frac{2(1-\theta_1-\theta_2)}{\theta_1(2-\theta_1-2\theta_2)} - \frac{2}{-2\theta_1-\theta_2 + 2} - \frac{2}{1-\theta_1-\theta_2} && 
\frac{1}{\theta_2}+\frac{2(1-\theta_2-\theta_1)}{\theta_1(2-\theta_2-2\theta_1)} - \frac{2}{-2\theta_2-\theta_1 + 2} - \frac{2}{1-\theta_1-\theta_2}
\end{bmatrix} := \boldsymbol{0}
\end{aligned}
$$  
Taking second derivatives, we obtain the Hessian matrix:  

$$
\begin{aligned}
\nabla^2l(\theta_1,\theta_2) &= \boldsymbol{H}(\theta_1,\theta_2) \\
&=
\begin{bmatrix}
\frac{\partial l}{\theta_1, \theta_1} && \frac{\partial l}{\theta_1, \theta_2} \\
\frac{\partial l}{\theta_1, \theta_2} && \frac{\partial l}{\theta_2, \theta_2} \\
\end{bmatrix}
\end{aligned}
$$  
where  
$$
\begin{aligned}
H_{[1,1]} &= - \frac{-2\theta_1-2\theta_2+2}{\theta_1^2(2-\theta_1-2\theta_2)} - 
\frac{1}{\theta_1^2} - 
\frac{-2\theta_1 -2\theta_2 + 2}{\theta_1(2-\theta_1-2\theta_2)} - 
\frac{2}{\theta_1(2-\theta_1-2\theta_2)} - 
\frac{4}{(-2\theta_1-\theta_2+2)^2} - 
\frac{2}{(1-\theta_1-\theta_2)^2}\\
H_{[1,2]} &= H_{[2,1]} = \frac{-2(\theta_1-2\theta_2+2)}{\theta_2(-2\theta_1-\theta_2+2)^2} - 
\frac{2}{(2-\theta_1-2\theta_2)^2} - 
\frac{2}{(1-\theta_1-\theta_2)^2} -
\frac{2}{\theta_2(-2\theta_1-\theta_2+2)} \\
H_{[1,1]} &= \frac{-2\theta_1-2\theta_2+2}{\theta_2^2(2-\theta_2-2\theta_1)} - 
\frac{1}{\theta_2^2} - 
\frac{-2\theta_1 -2\theta_2 + 2}{\theta_2(2-\theta_2-2\theta_1)} - 
\frac{2}{\theta_2(2-\theta_2-2\theta_1)} - 
\frac{4}{(-2\theta_2-\theta_1+2)^2} - 
\frac{2}{(1-\theta_1-\theta_2)^2}
\end{aligned}
$$

## (c)  
Compute the information matrix  

The information matrix $\mathcal{\boldsymbol{I}(\theta_1,\theta_2)} = -\nabla^2l(\theta_1, \theta_2)$, so  
$$
\begin{aligned}
I_{[1,1]} &=   \frac{-2\theta_1-2\theta_2+2}{\theta_1^2(2-\theta_1-2\theta_2)} + 
\frac{1}{\theta_1^2} + 
\frac{-2\theta_1 -2\theta_2 + 2}{\theta_1(2-\theta_1-2\theta_2)} + 
\frac{2}{\theta_1(2-\theta_1-2\theta_2)} + 
\frac{4}{(-2\theta_1-\theta_2+2)^2} + 
\frac{2}{(1-\theta_1-\theta_2)^2}\\
I_{[1,2]} &= I_{[2,1]} = \frac{2(-2\theta_1-2\theta_2+2)}{\theta_2(-2\theta_1-\theta_2+2)^2} + 
\frac{2}{(2-\theta_1-2\theta_2)^2} + 
\frac{2}{(1-\theta_1-\theta_2)^2} + 
\frac{2}{\theta_2(-2\theta_1-\theta_2+2)} \\
I_{[1,1]} &= \frac{-2\theta_1-2\theta_2+2}{\theta_2^2(2-\theta_2-2\theta_1)} + 
\frac{1}{\theta_2^2} + 
\frac{-2\theta_1 -2\theta_2 + 2}{\theta_2(2-\theta_2-2\theta_1)} + 
\frac{2}{\theta_2(2-\theta_2-2\theta_1)} + 
\frac{4}{(-2\theta_2-\theta_1+2)^2} + 
\frac{2}{(1-\theta_1-\theta_2)^2}
\end{aligned}
$$

## (d)  
Suppose $y_1 = 17$, $y_2 = 182$, $y_3=60$, and $y_4 = 176$, so that $n=435$. Set $\pi_j=y_j/n$ for the first two groups and solve for $\theta_1$ and $\theta_2$ to obtain the starting values $\theta_1^{(0)}=0.263$ and $\theta_2^{(0)}=0.074$. Compute the MLEs using (i) Newton's method analytically with derivatives, (ii) Newton's method with numerical derivatives, and (iii) the scoring method. Use a maximum of three iterations for each method. For each method, complete the table below:  











